### ISSUE TITLE
Requires Cumulus-Plus 

### ISSUE THREAD

**Issue by Adrion** [initbizlab/oc-cumulus-theme#2]
It seems that your template requires `clusterDashboard`, provided by [Cumulus-plus](https://octobercms.com/plugin/initbiz-cumulusplus).

It's not mention into theme.yaml or on october website requirements : https://octobercms.com/theme/initbiz-cumulus
You may add it. 

I was looking for a fast way to test CumulusCore to see if it match our needs. 
May be we can create a second template without the premium feature to allow fast test ?

**Comment by tomaszstrojny** [comment]
You are right, we have moved `clusterDashboard` to new plugin recently and haven't updated the theme. In a few days this will be updated :)

**Comment by tomaszstrojny** [comment]
While working on a different feature we are waiting for new version of `RainLab.Pages` plugin. I just hot fixed this issue, so that no problems with the component exists.

After we push new version of Cumulus the theme will be updated as well.
